#!/bin/bash

mkdir results

for i in ./pockets/*; do
    name=`basename $i`
    echo $name
    mkdir ./results/$name
    cd ./results/$name
    mdpocket --trajectory_file ../../cutted.trr --trajectory_format trr --selected_pocket ../../pockets/$name -f ../../example.pdb  
    cd ../../
done

